### PR TITLE
Fix incorrect matching of quoted and commented brackets

### LINKED ISSUE #78: Brackets being matched in comments and strings
Related: lee-dohm/emacs-flow#3

Repro case can be found (with permission) at: https://gist.github.com/debtosh/e5b25c7719867ec56382
## Repro Steps
1. Open a new file
2. Paste in the text from the Gist linked above
3. Set the grammar to C++
4. Place the cursor after the brace at the end of line 2

**Expected:** Matches brace on line 33
**Actual:** Does not match
1. Place the cursor after the brace _in the comment_ at the end of line 20

**Expected:** Does not match
**Actual:** Matches brace on line 33

If the braces at the end of the comment lines are deleted, all braces match as they would be expected to.

### PR DESCRIPTION
**Pull request by john-f**
Also fixes incorrect matching of brackets in regular expressions.

Also adds tests for these cases.

This resolves #78 (and its many duplicates).

### CODE REVIEW

**Comment by 50Wliu** [comment]
I think that if the brackets are exclusively within the comments/strings then they should still get matched.

**Comment by john-f** [comment]
@50Wliu 

Comments aren't usually code (and thus there's little utility to bracket matching in them).

Additionally, code that is commented is often incomplete or a single line, so, again, bracket matching in comments provides little value.

Commented code also loses all other syntax highlighting, so not bracket matching would be consistent with that behavior.

**Comment by 50Wliu** [comment]
You failed to address the strings portion: I do use bracket matching in strings, such as when writing regex.

That said, I don't consider my request to be a strict blocker for merging this.  It can always be discussed/added later.

**Comment by rtapella** [comment]
I'd suggest that skipping comments/code is the desired behavior. There is no strict syntactic requirement to have matching brackets in free text. One might intentionally have mis-matched brackets in comments/strings; including those in a bracket search would mess up the code-bracket matching. An as example  :)

I could imagine a separate feature that does bracket matching specifically within a single string, or within a comment block.

PS THANK YOU john-f

**Comment by 50Wliu** [comment]
At a glance this looks ok to me.

File: lib/bracket-matcher-view.coffee [hunk 1]
```diff
@@ -24,7 +25,9 @@ class BracketMatcherView
     @tagFinder = new TagFinder(@editor)
     @pairHighlighted = false
     @tagHighlighted = false
+    @commentOrStringSelector = SelectorCache.get('comment.* | string.*')
 
+    @subscriptions.add @editor.onDidTokenize(@updateMatch)
```
Comment (kuychaco) [inline lib/bracket-matcher-view.coffee]: hey @john-f, what was the thought behind this addition? It's not quite clear to me why it's necessary. Commenting it out and running the tests, it seems that they all pass.

Comment (john-f) [inline lib/bracket-matcher-view.coffee]: So, this line is a fix for a special case that only happens when the following two conditions are **both** met:

1) a file is opened **or** the file grammar is changed (ie: from plain text to javascript)
2) the cursor initially starts on a commented bracket **or** a bracket in a string.

Normally, you'd get an incorrect match in this situation.

This happens because bracket matching occurs before tokenization is enabled. The editor doesn't know what's a comment or string yet, so incorrect matches are made.<sup>[1]</sup>

Adding this listener forces an update after tokenization kicks in, thus correcting the initial bad match. The listener is only triggered once, on file load or grammar change, so it's fairly efficient.

[1] Incidentally, these matches will be corrected on the first cursor move, but it shouldn't happen in the first place.
