### PR TITLE
Find brackets to highlight using the Tree-sitter syntax tree

### LINKED ISSUE #348: [performance]: Low frame rate when the matching bracket spans several hundreds of lines
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When trying to type in front of a bracket and the corresponding closing bracket is located several hundreds of lines later, the editor's frame rate drops significantly and typed characters appear almost half a second later.

**Example code:**

```js
describe('test', () => {
//      ^ start typing here with cursor in front of the opening (
// ... lots and lots of JS here (1200 SLOC)
})
```

### Steps to Reproduce

1. Open a huge file (tested on JavaScript file with big test suite)
1. Place the cursor in front of the opening bracket while the matching closing bracket is located several hundreds of lines later
1. Attempt to type some characters
1. Observe editor lag

**Expected behavior:** No editor lag, smooth typing experience, feelings of joy and happiness

**Actual behavior:** typed characters appear after several hundreds of ms, editor feels unresponsive, feelings of anger and frustration

**Reproduces how often:** 100% of the time, but only when the matching bracket is very very far away

### Versions

```
Atom    : 1.26.0-beta1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
OS: MacOS 10.13.4
```

### Additional Information

I am attaching Chrome's performance profile for further inspection. From the stack traces included there I concluded that this is likely a problem with the bracket-matcher package. Disabling the package resolves the issue described here.

I have not looked at the code at all, but it almost seems that `bracket-matcher` is searching for the matching bracket on each keystroke even though none of the brackets are actually modified, only the content in front of them. 🤔

[bracket-matcher.json.zip](https://github.com/atom/bracket-matcher/files/1885346/bracket-matcher.json.zip)

### LINKED ISSUE #355: Tag matching doesn't work in HTML with tree-sitter enabled
*Edit by @rsese to add issue template details*

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Bracket matching in HTML doesn't work with tree-sitter enabled.

### Steps to Reproduce

1. Enable tree-sitter `Settings > Core > Use Tree Sitter Parsers`
2. Create and save a file `test.html` with the `html` snippet content:

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  </body>
</html>
```

3. Click in the `<body>` tag.

**Expected behavior:** [What you expect to happen]

Expect the `<\body>` tag to be highlighted.

**Actual behavior:** [What actually happens]

The `<\body>` tag isn't highlighted.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```
$ atom-nightly  -v
Atom    : 1.31.0-nightly3
Electron: 2.0.6
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

macOS 10.12.6

### Additional Information

If you disable tree-sitter, the tag matching works.

---

always worked in all files. after updating Atom and packages 2 days ago (done on 2d of August 2018), Matcher stopped working in plain HTML files.

I disabled all packages and left on the core ones, still not working..

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
### Description of the Change

Currently, this package finds matching brackets by [performing a regex search and keeping track of the nesting level of bracket characters](https://github.com/atom/bracket-matcher/blob/24f4d0282e6e6ccb5fd4fbc70939e69a6a9ff21b/lib/bracket-matcher-view.js#L160-L189). The code for finding matching HTML tags is [even more complicated](https://github.com/atom/bracket-matcher/blob/24f4d0282e6e6ccb5fd4fbc70939e69a6a9ff21b/lib/tag-finder.js).

In this PR, I've updated the package to find matching tokens using syntax trees provided by [Tree-sitter](https://blog.github.com/2018-10-31-atoms-new-parsing-system/), when they are available.

### Benefits

The performance of bracket matching is vastly improved. Here's a flame graph that I recorded in the current version of Atom when moving the cursor across [this opening parenthesis](https://github.com/atom/atom/blob/36d185fa4d1e2b56d3d4a2ee2ce977e83984030c/spec/text-editor-component-spec.js#L31) in Atom's `text-editor-component-spec.js`.

screen shot 2018-11-16 at 2 46 03 pm

This operation took **300ms**.

Here's a flame graph that I recorded of the same operation with this fix:

screen shot 2018-11-16 at 3 08 30 pm

The operation now takes **0.75ms**; the syntax tree makes the operation basically free.

### Possible Drawbacks

This improvement only takes effect for languages with Tree-sitter parsers.

### Applicable Issues

Fixes #348
Fixes #355

### CODE REVIEW

File: lib/bracket-matcher-view.js [hunk 1]
```diff
@@ -216,6 +221,28 @@ class BracketMatcherView {
...
+            } else if (lastChild.firstChild.type === '<' && lastChild.child(1).type === '/') {
+              endRange = lastChild.child(2).range
+            }
+          }
+          return true
+        }
+      }
+    })
+    if (startRange && endRange) return {startRange, endRange}
+  }
```
Comment (maxbrunsfeld) [inline lib/bracket-matcher-view.js]: This one method takes the place of the [the `TagFinder` class](https://github.com/atom/bracket-matcher/blob/24f4d0282e6e6ccb5fd4fbc70939e69a6a9ff21b/lib/tag-finder.js).
